// <auto-generated />
using System;
using AgencyCursor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgencyCursor.WebApp.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20260220013111_AddAppointmentInterpreterTeam")]
    partial class AddAppointmentInterpreterTeam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AgencyCursor.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmployeeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterpreterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceDetails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterpreterId");

                    b.HasIndex("RequestId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AgencyCursor.Models.AppointmentInterpreter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterpreterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("InterpreterId");

                    b.ToTable("AppointmentInterpreters");
                });

            modelBuilder.Entity("AgencyCursor.Models.Interpreter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Certification")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegisteredWithAgency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Languages")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interpreters");
                });

            modelBuilder.Entity("AgencyCursor.Models.InterpreterEmailLog", b =>
                {
                    b.Property<int>("InterpreterEmailLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterpreterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InterpreterEmailLogId");

                    b.HasIndex("InterpreterId");

                    b.HasIndex("RequestId");

                    b.ToTable("InterpreterEmailLogs");
                });

            modelBuilder.Entity("AgencyCursor.Models.InterpreterResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterpreterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseToken")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterpreterId");

                    b.HasIndex("RequestId");

                    b.ToTable("InterpreterResponses");
                });

            modelBuilder.Entity("AgencyCursor.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InterpreterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("InterpreterId");

                    b.HasIndex("RequestorId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("AgencyCursor.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumerNames")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderPreference")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndividualType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternationalOther")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfIndividuals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherInterpreter")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredInterpreterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredInterpreterName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specializations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfService")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfServiceOther")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreferredInterpreterId");

                    b.HasIndex("RequestorId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AgencyCursor.Models.Requestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Requestors");
                });

            modelBuilder.Entity("AgencyCursor.Models.ZipCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminCode1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminCode2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminCode3")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminName1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminName2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminName3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PlaceName")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZipCodes");
                });

            modelBuilder.Entity("AgencyCursor.Models.Appointment", b =>
                {
                    b.HasOne("AgencyCursor.Models.Interpreter", "Interpreter")
                        .WithMany()
                        .HasForeignKey("InterpreterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyCursor.Models.Request", "Request")
                        .WithMany("Appointments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interpreter");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AgencyCursor.Models.AppointmentInterpreter", b =>
                {
                    b.HasOne("AgencyCursor.Models.Appointment", "Appointment")
                        .WithMany("AppointmentInterpreters")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyCursor.Models.Interpreter", "Interpreter")
                        .WithMany("AppointmentInterpreters")
                        .HasForeignKey("InterpreterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Interpreter");
                });

            modelBuilder.Entity("AgencyCursor.Models.InterpreterEmailLog", b =>
                {
                    b.HasOne("AgencyCursor.Models.Interpreter", "Interpreter")
                        .WithMany()
                        .HasForeignKey("InterpreterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyCursor.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interpreter");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AgencyCursor.Models.InterpreterResponse", b =>
                {
                    b.HasOne("AgencyCursor.Models.Interpreter", "Interpreter")
                        .WithMany()
                        .HasForeignKey("InterpreterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgencyCursor.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interpreter");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("AgencyCursor.Models.Invoice", b =>
                {
                    b.HasOne("AgencyCursor.Models.Appointment", "Appointment")
                        .WithMany("Invoices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgencyCursor.Models.Interpreter", "Interpreter")
                        .WithMany("Invoices")
                        .HasForeignKey("InterpreterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgencyCursor.Models.Requestor", "Requestor")
                        .WithMany("Invoices")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Interpreter");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("AgencyCursor.Models.Request", b =>
                {
                    b.HasOne("AgencyCursor.Models.Interpreter", "PreferredInterpreter")
                        .WithMany("PreferredForRequests")
                        .HasForeignKey("PreferredInterpreterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgencyCursor.Models.Requestor", "Requestor")
                        .WithMany("Requests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreferredInterpreter");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("AgencyCursor.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentInterpreters");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AgencyCursor.Models.Interpreter", b =>
                {
                    b.Navigation("AppointmentInterpreters");

                    b.Navigation("Invoices");

                    b.Navigation("PreferredForRequests");
                });

            modelBuilder.Entity("AgencyCursor.Models.Request", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AgencyCursor.Models.Requestor", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
